version: "2"
services:
  nginx-react:
    container_name: lavender-ui-app
    image: nehemhub/lavender-ui:latest
    build:
      context: .
      dockerfile: Dockerfile
    platform:
      linux/amd64
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production